### ISSUE TITLE
_this.spreadStdoutAndStdErr is not a function

### ISSUE THREAD

**Issue by Dattaya** [s00d/webpack-shell-plugin-next#11]
Hi, I tried to update `webpack-shell-plugin-next` to 1.1.1 from 0.6.4 but couldn't due to this error. Recently you removed `prototype` from `WebpackShellPlugin.spreadStdoutAndStdErr`, and on [line 248](https://github.com/s00d/webpack-shell-plugin-next/blob/master/lib/index.js#L248) this function is called as though it's a member of an object instance:
```js
_this.spreadStdoutAndStdErr(child_process_1.exec(script, _this.putsAsync(resolve)));
```

**Comment by s00d** [comment]
hello. try 1.1.2

**Comment by Dattaya** [comment]
Thanks, now everything's working just fine 🎉
