### ISSUE TITLE
Max buffer exceeded

### ISSUE THREAD

**Issue by wayofthefuture** [s00d/webpack-shell-plugin-next#12]
I am on WIndows 10 platform.

Unfortunately, in a relatively short amount of time, I get a "stdout maxBuffer exceeded" error. I checked the code and maxBuffer is passed as MAX_SAFE_INTEGER for the execSync function but still to no avail it still kicks out. I am certain I haven't reached the max buffer. Do you think the MAX_SAFE_INTEGER is too large?

Thanks

**Comment by s00d** [comment]
Hey. Can you send example code?

**Comment by s00d** [comment]
I have released a new version 2.1.1. try to use it
