### ISSUE TITLE
Question / Feature request: run command on watchRun

### ISSUE THREAD

**Issue by boojum** [s00d/webpack-shell-plugin-next#14]
Is there a _clean_ way to run a command when both, `NODE_ENV=development` and `npm start` was executed? Let me elaborate with code what I mean.

`package.json`:
```
  "scripts": {
    "clean": "rimraf dist",
    "prestart": "npm run clean",
    "start": "webpack",
    "dev": "nodemon dist/server.js",
    "build": "webpack --progress"
  }
```

`webpack.config.js`:
```
require('dotenv/config')
const WebpackShellPlugin = require('webpack-shell-plugin-next')

const { NODE_ENV = 'production' } = process.env

module.exports = {
  mode: NODE_ENV,
  watch: NODE_ENV === 'development',
  plugins: [
    ...(NODE_ENV === 'production'
      ? []
      : [
          new WebpackShellPlugin({
            onBuildEnd: {
              scripts: ['npm run dev'],
              blocking: false,
              parallel: false,
            },
          }),
        ]),
  ],
}
```

For simplicity sake both configs are abridged to the relevant parts only. Behaviour, with the above setup, is as follows:

`npm start` in production: only `webpack` is executed
`npm start` in development: `webpack` and `nodemon` are executed
`npm run build` in production: only `webpack` is executed
`npm run build` in development: `webpack` and `nodemon` are executed

This _is_ the expected behaviour, no bugs here.
Is there a _clean_ way to only run `webpack-shell-plugin-next` when `NODE_ENV=development` AND when the preceding command was `npm start`? By clean I mean something not requiring any modification to the `npm-run-scripts` in `package.json`. Something along the lines of:
```
  plugins: [
    ...(NODE_ENV === 'production' || !npm start
      ? []
      : [
          new WebpackShellPlugin({
            onBuildEnd: {
              scripts: ['npm run dev'],
              blocking: false,
              parallel: false,
            },
          }),
        ]),
  ],
```

Alternatively, is implementing `onWatchRun` something you might consider? `webpack` compiler hooks expose precisely that via [watchRun](https://webpack.js.org/api/compiler-hooks/#watchrun).

**Comment by s00d** [comment]
Hello. Try to do so:
```
const config = { 
  mode: NODE_ENV,
  watch: NODE_ENV === 'development',
  plugins: [
    ....
  ],
  ....
}
if (NODE_ENV !== 'production') {
  config.plugins = (config.plugins || []).concat([
    new WebpackShellPlugin({
            onBuildEnd: {
              scripts: ['npm run dev'],
              blocking: false,
              parallel: false,
            },
    }),
 ]);
}
module.exports = config;
```
I'll try to add later onWatchRun

**Comment by s00d** [comment]
onWatchRun been added, read [here](https://github.com/s00d/webpack-shell-plugin-next/blob/master/README.md)
