### ISSUE TITLE
onBuildExit no longer fires in --watch mode

### ISSUE THREAD

**Issue by mpartel** [s00d/webpack-shell-plugin-next#15]
In an older project `onBuildExit` fires every time `webpack --watch` finishes a build.
In a new project created today, it only fires after the first build.

Old project deps:
```
    "webpack": "^4.35.0",
    "webpack-cli": "^3.3.4",
    "webpack-shell-plugin-next": "^0.6.4"
```

New project deps::
```
    "webpack": "^4.42.1",
    "webpack-cli": "^3.3.11",
    "webpack-shell-plugin-next": "^1.1.7"
```

**Comment by s00d** [comment]
hello. Publish new version. Added onDoneWatch, try it.

**Comment by mpartel** [comment]
Works perfectly, thanks!
