### ISSUE TITLE
Any way to get scripts run before HMR for webpack-dev-server compiling runs?

### ISSUE THREAD

**Issue by vgrynch** [s00d/webpack-shell-plugin-next#20]
I have tried all and every hooks from API and none are executed when webpack dev server runs compiling when some file changes. Any way to catch that moment and run scripts before HMR compiling?

**Comment by vgrynch** [comment]
Versions:
Webpack 4.43.0, node v8.15.1, webpack-shell-plugin-next 1.1.6. Or is it required to upgrade to webpack 5?

**Comment by s00d** [comment]
Good afternoon, unfortunately the onAfterDone event only appeared in webpack 5, I can't do anything with 4 version :(
