### ISSUE TITLE
[Feature Request] option to skip non-onBuildError hooks after error, also pass errors to callbacks

### ISSUE THREAD

**Issue by Enteleform** [s00d/webpack-shell-plugin-next#23]
I have a setup similar to the following:

```ts
new WebpackShellPluginNext({
  onAfterDone: {
    scripts: [
      () => console.clear(),
      "node ./index.js",
    ]
  }
})
```

The issue I'm running into is that if the `watch` rebuild fails, my scripts are still executed.

This results in :
  - `console.clear` removing the error log from my terminal
  - execution of the previously built version of `index.js`

&nbsp;  

-----

&nbsp;  

I managed to work around this with the following configuration:

```ts
let has_BuildError = false

export default {
  plugins: [
    new WebpackShellPlugin({
      onBuildError: {
        scripts:[() => {has_BuildError = true}]
      },
      onAfterDone: {
        scripts: [()=>{
          if(!has_BuildError){
            console.clear()
            execSync("node ./index.js", {stdio:"inherit"})
          }
          
          has_BuildError = false
        }]
      },
    })
  ]
}
```

However, this solution results in boilerplate which could be avoided by having an `onError` option for relevant hooks:

```ts
onAfterDone: {
  onError: "skip", // ("skip" | "execute")
  scripts: [...],
}
```

I think `skip` would make sense as the default value, as it is the safer of the two options. That way, script execution after an error would be opt-in only, with the developer understanding that they could potentially have an incomplete build state.

&nbsp;  
Another thing that would be useful in this scenario is a way for the developer to know whether or not an error occurred. I propose passing the errors to `scripts` callbacks:

```ts
onAfterDone: {
  onError: "execute",
  scripts: [(errors: WebpackError[] | undefined) => {
    if(errors)
      {/* do something */}
    else
      {/* do something else */}
  }],
```

**Comment by s00d** [comment]
Hello. Please read the info in the pull request #24

**Comment by Yehonal** [comment]
> ```ts
> let has_BuildError = false
> ```

Thanks for the workaround!
