### ISSUE TITLE
Issue with npm script not running on Windows OS

### ISSUE THREAD

**Issue by leepowelldev** [s00d/webpack-shell-plugin-next#28]
Hi. We have the latest version of this plugin running on our webpack 5 config:

```
// webpack.config.js

new WebpackShellPlugin({
  onBuildStart: {
    scripts: ['npm run generateTypedCss'],
    blocking: true,
    parallel: false
  }
}),
```

```
// package.json

"scripts": {
  "generateTypedCss": "tcm Content/scripts"
}
```

And it runs fine on Mac OS, however on Windows OS it doesn't run the npm script. We get the 'Executing pre-build scripts', but then it goes straight into the webpack build with no output. On Mac OS we get the full output of `typed-css-modules`. 

I don't suppose you have any ideas on what could be happening? There's no errors, and no other logging to give us an idea of what the issue is.

**Comment by leepowelldev** [comment]
Also tried with:

```
scripts: [`npx typed-css-modules ${path.resolve(__dirname, publicPath)}`]
```

And that did not work either

**Comment by s00d** [comment]
hello!
try 2.2.2.
Added some fixes and error logging.
if it doesn't help, enable safe: true
```
 new WebpackShellPlugin({
      safe: true,
```

**Comment by leepowelldev** [comment]
Thanks. I’ll give it a go.

**Comment by ws-craig** [comment]
That's fixed the same issues I had. Thanks.

**Comment by craigjamesdobson** [comment]
That's fixed the same issues I had. Thanks.

**Comment by leepowelldev** [comment]
Appreciated - this seems to have done the job.
