### ISSUE TITLE
rm -r some_folder/* does not work

### ISSUE THREAD

**Issue by geekox86** [s00d/webpack-shell-plugin-next#3]
Greetings,

I tried with the absolute path with no luck.
The issue seems to be with the wildcard.

```
new WebpackShellPlugin({
  onBuildStart: { scripts: ['rm -r www/*'] },
  onBuildEnd: { scripts: ['rm www/index.js'] }
}),
```

onBuildEnd works but onBuildStart does not work with this error:
Executing pre-build scripts
rm: www/*: No such file or directory

Any clue?

**Comment by s00d** [comment]
```
onBuildStart: { scripts: ['rm -r ' + path.join(__dirname, 'www/*')] },

```
