### ISSUE TITLE
cd command not run and zip command not work?

### ISSUE THREAD

**Issue by wiwengweng** [s00d/webpack-shell-plugin-next#30]
Hi，right now I have some scripts running onBuildExit as follows, but the `cd` command is not working, and `zip` command failed?

os: MacOS

I can run `zip -r test.zip * ` in the console without issue. Then I try to do this in a script with nodejs and this plugin. I import this plugin and then call it to run script when the build process exits. I try to zip some files in the `./build/ ` folder, just something like the screenshot.
![image](https://user-images.githubusercontent.com/1968042/115321371-3ded1700-a1b6-11eb-8817-2a576623655a.png)

I failed in the 2nd step, to cd `./build && ...`, because I see the console shows no such file or directory when it tries to `cp ./build/xxx.mpk `to other directory. I check the `./build ` directory, the xxx.mpk file is not generated.

Can I examine why this script failed?

**Comment by s00d** [comment]
Hello. Please use __dirname in your scripts

```
path.join(__dirname, dir)
```
