### ISSUE TITLE
Incorrect information in README

### ISSUE THREAD

**Issue by N247S** [s00d/webpack-shell-plugin-next#33]
I was scratching my head for a while on the configuration passed to the constructor, till I found out some information might be incorrect/misleading (I suspect).

Basically I wanted to use the plugin to automatically run a test script after each build during webpack-watching. So I tried setting the `swallowError` to `true` as suggested in the README. Turns out it has to be set on root-level, not scoped to a single event. The way it is currently displayed in the README file suggest it is part of the event-scoped properties, so I would be able to do something like:

```javascript
new WebpackShellPluginNext(
{
  onBuildExit: {
    scripts: ["npm run test"],
    blocking: false,
    parallel: false,
    logging: true,
    swallowError: true,
  },
})
```

After digging in to the code I found that only the `blocking` and `parallel` property is supported at event-scoped properties. So all other properties are simply ignored.

Not sure if that is a bug (a future feature) or simply incorrect/misleading information.

**Comment by s00d** [comment]
hello. fixed, thanks.
