### ISSUE TITLE
CHMOD command not working with glob.

### ISSUE THREAD

**Issue by lucasantunes-ciandt** [s00d/webpack-shell-plugin-next#35]
I'm trying to `chmod +x` the entire `.git/hooks` folder because CopyWebpackPlugin doesn't copy the files with the correct permissions.

Unfortunately I'm being forced to `chmod +x ../.git/hooks/filename` for every single file I want to chmod, because if I try `chmod +x ../.git/hooks/*` I get `chmod: cannot access '../.git/hooks/*: No such file or directory`

Tried with both the `webpack-shell-plugin` plugin and this one.

**Comment by lucasantunes-ciandt** [comment]
I circumvented it by creating a `.sh` file with the command I wanted to run and using `bash scripts/onBuildEnd.sh`. It shouldn't be needed for a single and simple command, though. :disappointed:

**Comment by s00d** [comment]
hello. need use full path 
```js
"chmod +x " + path.join(__dirname, '../.git/hooks/filename')
```

**Comment by lucasantunes-ciandt** [comment]
I tried it with full path as well. I wasn't trying to chmod a file, but all files within a directory, _e.g._ `path.join(__dirname, '../.git/hooks/*')`. From what I could notice, it seems the plugin tries to output the command as `chmod +x '../.git/hooks/*'`, which is indeed invalid, as quotes are explicitly used for filenames. It should output the command "as is", so that the glob pattern can be expanded.

**Comment by s00d** [comment]
Plugin doesn't change the path. Can you create a repository with an example? I'll try to understand what the problem is.
