### ISSUE TITLE
Using with in-memory webpack-dev-server

### ISSUE THREAD

**Issue by vagonpidarasov** [s00d/webpack-shell-plugin-next#9]
# Overview
I'd like to execute some command (which creates a file) with webpack-dev-server.

# Actual behaviour
File appears in file system

# Expected Behaviour
File appears in-memory of webpack-dev-server

**Comment by s00d** [comment]
see Function in scripts or you . can use js file
```
 scripts: [
   'node ./test/file.js',
```
